# Discipline

In [3]:
import pandas as pd
df = pd.read_csv('data/aiu_ineligible_persons.csv')

## Discipline distribution

In [24]:
df.groupby('Country Name')['Discipline 2'].nunique().nlargest(5)

Country Name
India      7
Russia     7
Kenya      6
Kuwait     6
Bahrain    5
Name: Discipline 2, dtype: int64

In [25]:
df.groupby('Country Name')['Discipline 1'].nunique().nlargest(5)

Country Name
Russia     11
India       8
Ukraine     5
Belarus     3
China       3
Name: Discipline 1, dtype: int64

## Athlete Support Personnel

In [26]:
df.query('Role == "Athlete Support Personnel"').groupby('Country Name')['Role'].value_counts().reset_index(name='Count').sort_values('Count', ascending=False)

    Country Name                       Role  Count
0          China  Athlete Support Personnel      7
1         France  Athlete Support Personnel      1
2         Greece  Athlete Support Personnel      1
3  United States  Athlete Support Personnel      1

In [27]:
df.query('`Discipline 2` == "Athlete Support Personnel"').groupby('Country Name')['Discipline 2'].value_counts().reset_index(name='Count').sort_values('Count', ascending=False)

     Country Name               Discipline 2  Count
8         Türkiye  Athlete Support Personnel      8
2           China  Athlete Support Personnel      7
7          Russia  Athlete Support Personnel      6
3          France  Athlete Support Personnel      2
0     Afghanistan  Athlete Support Personnel      1
1          Brazil  Athlete Support Personnel      1
4          Greece  Athlete Support Personnel      1
5           India  Athlete Support Personnel      1
6         Romania  Athlete Support Personnel      1
9   United States  Athlete Support Personnel      1
10      not found  Athlete Support Personnel      1

In [10]:
df["ADRV Notes"].value_counts().head(3)

ADRV Notes
epo                                          60
evasion, refusal and or failure to submit    38
19-norandrosterone                           27
Name: count, dtype: int64